services:
  db:
    image: postgres:14.8-alpine
    user: "501"
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/pg-data
    volumes:
      - ./data/postgres_data:/pg-data
networks:
  default:
    driver: bridge
